# AUTO-GENERATED FILE. DO NOT EDIT.
# Generated by tools/gen_batch_mixins.py from src/py3r/behaviour/summary/summary.py
# Regenerate with: PYTHONPATH=src python -m tools.gen_batch_mixins
from __future__ import annotations

import warnings

from py3r.behaviour.util.collection_utils import BatchResult
from typing import Any
from typing import Literal
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from typing import Any, Literal


class SummaryCollectionBatchMixin:
    def save(
        self, dirpath: str, *, data_format: str = "parquet", overwrite: bool = False
    ) -> BatchResult:
        """
        Batch-mode wrapper for Summary.save across the collection.

        Save this Summary (including nested Features/Tracking) to a directory.

        See leaf method ``Summary.save`` for examples.
        """
        warnings.warn(
            "Direct batch passthrough via SummaryCollectionBatchMixin.save() is deprecated; "
            "use SummaryCollection.each.save() instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        _inplace = locals().get("inplace", True)
        if _inplace is False:
            return self.map_leaves(
                lambda _obj: getattr(_obj, "save")(
                    dirpath, data_format=data_format, overwrite=overwrite
                )
            )
        return self._invoke_batch("save", dirpath, data_format=data_format, overwrite=overwrite)

    def count_onset(self, column: str) -> BatchResult:
        """
        Batch-mode wrapper for Summary.count_onset across the collection.

        Count times boolean series changes False->True, ignoring nans.
        If first non-nan value is True, that counts as an onset.

        See leaf method ``Summary.count_onset`` for examples.
        """
        warnings.warn(
            "Direct batch passthrough via SummaryCollectionBatchMixin.count_onset() is deprecated; "
            "use SummaryCollection.each.count_onset() instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        _inplace = locals().get("inplace", True)
        if _inplace is False:
            return self.map_leaves(lambda _obj: getattr(_obj, "count_onset")(column))
        return self._invoke_batch("count_onset", column)

    def calculate_latency_nth_onset(
        self,
        column: str,
        target_value: str | float | int = None,
        threshold_op: Literal[">", ">=", "<=", "<", "==", "!="] = "==",
        nth_event: int = 1,
        integration_window=1,
    ) -> BatchResult:
        """
        Batch-mode wrapper for Summary.calculate_latency_nth_onset
        across the collection.

        Compute the latency (in seconds) of the N-th onset event in a feature column.

        See leaf method ``Summary.calculate_latency_nth_onset`` for examples.
        """
        warnings.warn(
            "Direct batch passthrough via SummaryCollectionBatchMixin.calculate_latency_nth_onset() is deprecated; "
            "use SummaryCollection.each.calculate_latency_nth_onset() instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        _inplace = locals().get("inplace", True)
        if _inplace is False:
            return self.map_leaves(
                lambda _obj: getattr(_obj, "calculate_latency_nth_onset")(
                    column, target_value, threshold_op, nth_event, integration_window
                )
            )
        return self._invoke_batch(
            "calculate_latency_nth_onset",
            column,
            target_value,
            threshold_op,
            nth_event,
            integration_window,
        )

    def time_true(self, column: str) -> BatchResult:
        """
        Batch-mode wrapper for Summary.time_true across the collection.

        See leaf method ``Summary.time_true`` for examples.
        """
        warnings.warn(
            "Direct batch passthrough via SummaryCollectionBatchMixin.time_true() is deprecated; "
            "use SummaryCollection.each.time_true() instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        _inplace = locals().get("inplace", True)
        if _inplace is False:
            return self.map_leaves(lambda _obj: getattr(_obj, "time_true")(column))
        return self._invoke_batch("time_true", column)

    def time_false(self, column: str) -> BatchResult:
        """
        Batch-mode wrapper for Summary.time_false across the collection.

        See leaf method ``Summary.time_false`` for examples.
        """
        warnings.warn(
            "Direct batch passthrough via SummaryCollectionBatchMixin.time_false() is deprecated; "
            "use SummaryCollection.each.time_false() instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        _inplace = locals().get("inplace", True)
        if _inplace is False:
            return self.map_leaves(lambda _obj: getattr(_obj, "time_false")(column))
        return self._invoke_batch("time_false", column)

    def total_distance(
        self, point: str, startframe: int | None = None, endframe: int | None = None
    ) -> BatchResult:
        """
        Batch-mode wrapper for Summary.total_distance across the collection.

        See leaf method ``Summary.total_distance`` for examples.
        """
        warnings.warn(
            "Direct batch passthrough via SummaryCollectionBatchMixin.total_distance() is deprecated; "
            "use SummaryCollection.each.total_distance() instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        _inplace = locals().get("inplace", True)
        if _inplace is False:
            return self.map_leaves(
                lambda _obj: getattr(_obj, "total_distance")(point, startframe, endframe)
            )
        return self._invoke_batch("total_distance", point, startframe, endframe)

    def sum_column(self, column: str) -> BatchResult:
        """
        Batch-mode wrapper for Summary.sum_column across the collection.

        Sum all non-NaN values in a `features.data` column and return as a SummaryResult.

        See leaf method ``Summary.sum_column`` for examples.
        """
        warnings.warn(
            "Direct batch passthrough via SummaryCollectionBatchMixin.sum_column() is deprecated; "
            "use SummaryCollection.each.sum_column() instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        _inplace = locals().get("inplace", True)
        if _inplace is False:
            return self.map_leaves(lambda _obj: getattr(_obj, "sum_column")(column))
        return self._invoke_batch("sum_column", column)

    def mean_column(self, column: str) -> BatchResult:
        """
        Batch-mode wrapper for Summary.mean_column across the collection.

        Mean of all non-NaN values in a `features.data` column and return as a SummaryResult.

        See leaf method ``Summary.mean_column`` for examples.
        """
        warnings.warn(
            "Direct batch passthrough via SummaryCollectionBatchMixin.mean_column() is deprecated; "
            "use SummaryCollection.each.mean_column() instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        _inplace = locals().get("inplace", True)
        if _inplace is False:
            return self.map_leaves(lambda _obj: getattr(_obj, "mean_column")(column))
        return self._invoke_batch("mean_column", column)

    def median_column(self, column: str) -> BatchResult:
        """
        Batch-mode wrapper for Summary.median_column across the collection.

        Median of all non-NaN values in a `features.data` column and return as a SummaryResult.

        See leaf method ``Summary.median_column`` for examples.
        """
        warnings.warn(
            "Direct batch passthrough via SummaryCollectionBatchMixin.median_column() is deprecated; "
            "use SummaryCollection.each.median_column() instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        _inplace = locals().get("inplace", True)
        if _inplace is False:
            return self.map_leaves(lambda _obj: getattr(_obj, "median_column")(column))
        return self._invoke_batch("median_column", column)

    def max_column(self, column: str) -> BatchResult:
        """
        Batch-mode wrapper for Summary.max_column across the collection.

        Max of all non-NaN values in a `features.data` column and return as a SummaryResult.

        See leaf method ``Summary.max_column`` for examples.
        """
        warnings.warn(
            "Direct batch passthrough via SummaryCollectionBatchMixin.max_column() is deprecated; "
            "use SummaryCollection.each.max_column() instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        _inplace = locals().get("inplace", True)
        if _inplace is False:
            return self.map_leaves(lambda _obj: getattr(_obj, "max_column")(column))
        return self._invoke_batch("max_column", column)

    def min_column(self, column: str) -> BatchResult:
        """
        Batch-mode wrapper for Summary.min_column across the collection.

        Min of all non-NaN values in a `features.data` column and return as a SummaryResult.

        See leaf method ``Summary.min_column`` for examples.
        """
        warnings.warn(
            "Direct batch passthrough via SummaryCollectionBatchMixin.min_column() is deprecated; "
            "use SummaryCollection.each.min_column() instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        _inplace = locals().get("inplace", True)
        if _inplace is False:
            return self.map_leaves(lambda _obj: getattr(_obj, "min_column")(column))
        return self._invoke_batch("min_column", column)

    def store(
        self, summarystat: Any, name: str, overwrite: bool = False, meta: Any = None
    ) -> BatchResult:
        """
        Batch-mode wrapper for Summary.store across the collection.

        stores a summary statistic and optional metadata, with optional overwrite protection

        See leaf method ``Summary.store`` for examples.
        """
        warnings.warn(
            "Direct batch passthrough via SummaryCollectionBatchMixin.store() is deprecated; "
            "use SummaryCollection.each.store() instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        _inplace = locals().get("inplace", True)
        if _inplace is False:
            return self.map_leaves(
                lambda _obj: getattr(_obj, "store")(summarystat, name, overwrite, meta)
            )
        return self._invoke_batch("store", summarystat, name, overwrite, meta)

    def make_bin(self, startframe: int, endframe: int) -> BatchResult:
        """
        Batch-mode wrapper for Summary.make_bin across the collection.

        creates a copy of the Summary object with the dataframes
        restricted from startframe to endframe, inclusive

        See leaf method ``Summary.make_bin`` for examples.
        """
        warnings.warn(
            "Direct batch passthrough via SummaryCollectionBatchMixin.make_bin() is deprecated; "
            "use SummaryCollection.each.make_bin() instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        _inplace = locals().get("inplace", True)
        if _inplace is False:
            return self.map_leaves(lambda _obj: getattr(_obj, "make_bin")(startframe, endframe))
        return self._invoke_batch("make_bin", startframe, endframe)

    def make_bins(self, numbins: int) -> BatchResult:
        """
        Batch-mode wrapper for Summary.make_bins across the collection.

        creates a list of Summary objects, with frames restricted into
        numbins even intervals.
        start/endpoints are duplicated between intervals to ensure no loss
        in e.g. distance calculations

        See leaf method ``Summary.make_bins`` for examples.
        """
        warnings.warn(
            "Direct batch passthrough via SummaryCollectionBatchMixin.make_bins() is deprecated; "
            "use SummaryCollection.each.make_bins() instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        _inplace = locals().get("inplace", True)
        if _inplace is False:
            return self.map_leaves(lambda _obj: getattr(_obj, "make_bins")(numbins))
        return self._invoke_batch("make_bins", numbins)

    def transition_matrix(self, column: str, all_states=None) -> BatchResult:
        """
        Batch-mode wrapper for Summary.transition_matrix across the collection.

        See leaf method ``Summary.transition_matrix`` for examples.
        """
        warnings.warn(
            "Direct batch passthrough via SummaryCollectionBatchMixin.transition_matrix() is deprecated; "
            "use SummaryCollection.each.transition_matrix() instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        _inplace = locals().get("inplace", True)
        if _inplace is False:
            return self.map_leaves(
                lambda _obj: getattr(_obj, "transition_matrix")(column, all_states)
            )
        return self._invoke_batch("transition_matrix", column, all_states)

    def count_state_onsets(self, column: str) -> BatchResult:
        """
        Batch-mode wrapper for Summary.count_state_onsets across the collection.

        counts the number of times a state is entered in a given column

        See leaf method ``Summary.count_state_onsets`` for examples.
        """
        warnings.warn(
            "Direct batch passthrough via SummaryCollectionBatchMixin.count_state_onsets() is deprecated; "
            "use SummaryCollection.each.count_state_onsets() instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        _inplace = locals().get("inplace", True)
        if _inplace is False:
            return self.map_leaves(lambda _obj: getattr(_obj, "count_state_onsets")(column))
        return self._invoke_batch("count_state_onsets", column)

    def time_in_state(self, column: str) -> BatchResult:
        """
        Batch-mode wrapper for Summary.time_in_state across the collection.

        See leaf method ``Summary.time_in_state`` for examples.
        """
        warnings.warn(
            "Direct batch passthrough via SummaryCollectionBatchMixin.time_in_state() is deprecated; "
            "use SummaryCollection.each.time_in_state() instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        _inplace = locals().get("inplace", True)
        if _inplace is False:
            return self.map_leaves(lambda _obj: getattr(_obj, "time_in_state")(column))
        return self._invoke_batch("time_in_state", column)
