# AUTO-GENERATED FILE. DO NOT EDIT.
# Generated by tools/gen_batch_mixins.py from src/py3r/behaviour/features/features.py
# Regenerate with: PYTHONPATH=src python -m tools.gen_batch_mixins
from __future__ import annotations

import warnings

from py3r.behaviour.util.collection_utils import BatchResult
import pandas as pd
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    import pandas as pd
    from sklearn.neighbors import KNeighborsRegressor
    from py3r.behaviour.classifier import BaseClassifier


class FeaturesCollectionBatchMixin:
    def save(
        self, dirpath: str, *, data_format: str = "parquet", overwrite: bool = False
    ) -> BatchResult:
        """
        Batch-mode wrapper for Features.save across the collection.

        Save this Features object (and its nested Tracking) to a self-describing directory.

        See leaf method ``Features.save`` for examples.
        """
        warnings.warn(
            "Direct batch passthrough via FeaturesCollectionBatchMixin.save() is deprecated; "
            "use FeaturesCollection.each.save() instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        _inplace = locals().get("inplace", True)
        if _inplace is False:
            return self.map_leaves(
                lambda _obj: getattr(_obj, "save")(
                    dirpath, data_format=data_format, overwrite=overwrite
                )
            )
        return self._invoke_batch("save", dirpath, data_format=data_format, overwrite=overwrite)

    def distance_between(self, point1: str, point2: str, dims=("x", "y")) -> BatchResult:
        """
        Batch-mode wrapper for Features.distance_between across the collection.

        See leaf method ``Features.distance_between`` for examples.
        """
        warnings.warn(
            "Direct batch passthrough via FeaturesCollectionBatchMixin.distance_between() is deprecated; "
            "use FeaturesCollection.each.distance_between() instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        _inplace = locals().get("inplace", True)
        if _inplace is False:
            return self.map_leaves(
                lambda _obj: getattr(_obj, "distance_between")(point1, point2, dims)
            )
        return self._invoke_batch("distance_between", point1, point2, dims)

    def within_distance(
        self, point1: str, point2: str, distance: float, dims=("x", "y")
    ) -> BatchResult:
        """
        Batch-mode wrapper for Features.within_distance across the collection.

        See leaf method ``Features.within_distance`` for examples.
        """
        warnings.warn(
            "Direct batch passthrough via FeaturesCollectionBatchMixin.within_distance() is deprecated; "
            "use FeaturesCollection.each.within_distance() instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        _inplace = locals().get("inplace", True)
        if _inplace is False:
            return self.map_leaves(
                lambda _obj: getattr(_obj, "within_distance")(point1, point2, distance, dims)
            )
        return self._invoke_batch("within_distance", point1, point2, distance, dims)

    def get_point_median(self, point: str, dims=("x", "y")) -> BatchResult:
        """
        Batch-mode wrapper for Features.get_point_median across the collection.

        Return the per-dimension median coordinate for a tracked point.

        See leaf method ``Features.get_point_median`` for examples.
        """
        warnings.warn(
            "Direct batch passthrough via FeaturesCollectionBatchMixin.get_point_median() is deprecated; "
            "use FeaturesCollection.each.get_point_median() instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        _inplace = locals().get("inplace", True)
        if _inplace is False:
            return self.map_leaves(lambda _obj: getattr(_obj, "get_point_median")(point, dims))
        return self._invoke_batch("get_point_median", point, dims)

    def define_boundary(
        self,
        points: list[str],
        scaling: float,
        scaling_y: float = None,
        centre: str | list[str] = None,
    ) -> BatchResult:
        """
        Batch-mode wrapper for Features.define_boundary across the collection.

        Static rescaled boundary from point medians.
        'centre' can be str or list[str]; median of those points or of boundary if None.
        'scaling' scales boundary; 'scaling_y' scales y-axis (default: same as scaling).

        See leaf method ``Features.define_boundary`` for examples.
        """
        warnings.warn(
            "Direct batch passthrough via FeaturesCollectionBatchMixin.define_boundary() is deprecated; "
            "use FeaturesCollection.each.define_boundary() instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        _inplace = locals().get("inplace", True)
        if _inplace is False:
            return self.map_leaves(
                lambda _obj: getattr(_obj, "define_boundary")(points, scaling, scaling_y, centre)
            )
        return self._invoke_batch("define_boundary", points, scaling, scaling_y, centre)

    def define_static_boundary(
        self,
        points: list[str],
        *,
        dims: tuple[str, str] = ("x", "y"),
        anchor: str | list[str] | None = None,
        scale_dim1: float = 1.0,
        scale_dim2: float = 1.0,
        name: str | None = None,
        overwrite: bool = False,
    ) -> BatchResult:
        """
        Batch-mode wrapper for Features.define_static_boundary across the collection.

        Define a static boundary from point medians and optional scaling.

        See leaf method ``Features.define_static_boundary`` for examples.
        """
        warnings.warn(
            "Direct batch passthrough via FeaturesCollectionBatchMixin.define_static_boundary() is deprecated; "
            "use FeaturesCollection.each.define_static_boundary() instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        _inplace = locals().get("inplace", True)
        if _inplace is False:
            return self.map_leaves(
                lambda _obj: getattr(_obj, "define_static_boundary")(
                    points,
                    dims=dims,
                    anchor=anchor,
                    scale_dim1=scale_dim1,
                    scale_dim2=scale_dim2,
                    name=name,
                    overwrite=overwrite,
                )
            )
        return self._invoke_batch(
            "define_static_boundary",
            points,
            dims=dims,
            anchor=anchor,
            scale_dim1=scale_dim1,
            scale_dim2=scale_dim2,
            name=name,
            overwrite=overwrite,
        )

    def define_dynamic_boundary(
        self,
        points: list[str],
        *,
        dims: tuple[str, str] = ("x", "y"),
        anchor: str | list[str] | None = None,
        scale_dim1: float = 1.0,
        scale_dim2: float = 1.0,
        name: str | None = None,
        overwrite: bool = False,
    ) -> BatchResult:
        """
        Batch-mode wrapper for Features.define_dynamic_boundary across the collection.

        Define a dynamic boundary from ordered point names and optional scaling.

        See leaf method ``Features.define_dynamic_boundary`` for examples.
        """
        warnings.warn(
            "Direct batch passthrough via FeaturesCollectionBatchMixin.define_dynamic_boundary() is deprecated; "
            "use FeaturesCollection.each.define_dynamic_boundary() instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        _inplace = locals().get("inplace", True)
        if _inplace is False:
            return self.map_leaves(
                lambda _obj: getattr(_obj, "define_dynamic_boundary")(
                    points,
                    dims=dims,
                    anchor=anchor,
                    scale_dim1=scale_dim1,
                    scale_dim2=scale_dim2,
                    name=name,
                    overwrite=overwrite,
                )
            )
        return self._invoke_batch(
            "define_dynamic_boundary",
            points,
            dims=dims,
            anchor=anchor,
            scale_dim1=scale_dim1,
            scale_dim2=scale_dim2,
            name=name,
            overwrite=overwrite,
        )

    def import_static_boundary(
        self,
        vertices: list[tuple[float, float]],
        *,
        dims: tuple[str, str] = ("x", "y"),
        name: str | None = None,
        overwrite: bool = False,
    ) -> BatchResult:
        """
        Batch-mode wrapper for Features.import_static_boundary across the collection.

        Escape hatch: import a precomputed static polygon in selected dims.

        See leaf method ``Features.import_static_boundary`` for examples.
        """
        warnings.warn(
            "Direct batch passthrough via FeaturesCollectionBatchMixin.import_static_boundary() is deprecated; "
            "use FeaturesCollection.each.import_static_boundary() instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        _inplace = locals().get("inplace", True)
        if _inplace is False:
            return self.map_leaves(
                lambda _obj: getattr(_obj, "import_static_boundary")(
                    vertices, dims=dims, name=name, overwrite=overwrite
                )
            )
        return self._invoke_batch(
            "import_static_boundary", vertices, dims=dims, name=name, overwrite=overwrite
        )

    def get_boundary(self, name: str) -> BatchResult:
        """
        Batch-mode wrapper for Features.get_boundary across the collection.

        Draft accessor for named boundary assets.

        See leaf method ``Features.get_boundary`` for examples.
        """
        warnings.warn(
            "Direct batch passthrough via FeaturesCollectionBatchMixin.get_boundary() is deprecated; "
            "use FeaturesCollection.each.get_boundary() instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        _inplace = locals().get("inplace", True)
        if _inplace is False:
            return self.map_leaves(lambda _obj: getattr(_obj, "get_boundary")(name))
        return self._invoke_batch("get_boundary", name)

    def list_boundaries(self) -> BatchResult:
        """
        Batch-mode wrapper for Features.list_boundaries across the collection.

        Return a compact table of named boundaries on this Features object.

        See leaf method ``Features.list_boundaries`` for examples.
        """
        warnings.warn(
            "Direct batch passthrough via FeaturesCollectionBatchMixin.list_boundaries() is deprecated; "
            "use FeaturesCollection.each.list_boundaries() instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        _inplace = locals().get("inplace", True)
        if _inplace is False:
            return self.map_leaves(lambda _obj: getattr(_obj, "list_boundaries")())
        return self._invoke_batch("list_boundaries")

    def within_boundary_static(
        self, point: str, boundary, boundary_name: str = None
    ) -> BatchResult:
        """
        Batch-mode wrapper for Features.within_boundary_static across the collection.

        See leaf method ``Features.within_boundary_static`` for examples.
        """
        warnings.warn(
            "Direct batch passthrough via FeaturesCollectionBatchMixin.within_boundary_static() is deprecated; "
            "use FeaturesCollection.each.within_boundary_static() instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        _inplace = locals().get("inplace", True)
        if _inplace is False:
            return self.map_leaves(
                lambda _obj: getattr(_obj, "within_boundary_static")(point, boundary, boundary_name)
            )
        return self._invoke_batch("within_boundary_static", point, boundary, boundary_name)

    def within_boundary_dynamic(
        self, point: str, boundary, boundary_name: str = None
    ) -> BatchResult:
        """
        Batch-mode wrapper for Features.within_boundary_dynamic across the collection.

        See leaf method ``Features.within_boundary_dynamic`` for examples.
        """
        warnings.warn(
            "Direct batch passthrough via FeaturesCollectionBatchMixin.within_boundary_dynamic() is deprecated; "
            "use FeaturesCollection.each.within_boundary_dynamic() instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        _inplace = locals().get("inplace", True)
        if _inplace is False:
            return self.map_leaves(
                lambda _obj: getattr(_obj, "within_boundary_dynamic")(
                    point, boundary, boundary_name
                )
            )
        return self._invoke_batch("within_boundary_dynamic", point, boundary, boundary_name)

    def within_boundary(self, point: str, boundary) -> BatchResult:
        """
        Batch-mode wrapper for Features.within_boundary across the collection.

        Main boundary inclusion API.

        See leaf method ``Features.within_boundary`` for examples.
        """
        warnings.warn(
            "Direct batch passthrough via FeaturesCollectionBatchMixin.within_boundary() is deprecated; "
            "use FeaturesCollection.each.within_boundary() instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        _inplace = locals().get("inplace", True)
        if _inplace is False:
            return self.map_leaves(lambda _obj: getattr(_obj, "within_boundary")(point, boundary))
        return self._invoke_batch("within_boundary", point, boundary)

    def distance_to_boundary(self, point: str, boundary) -> BatchResult:
        """
        Batch-mode wrapper for Features.distance_to_boundary across the collection.

        Main boundary distance API.

        See leaf method ``Features.distance_to_boundary`` for examples.
        """
        warnings.warn(
            "Direct batch passthrough via FeaturesCollectionBatchMixin.distance_to_boundary() is deprecated; "
            "use FeaturesCollection.each.distance_to_boundary() instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        _inplace = locals().get("inplace", True)
        if _inplace is False:
            return self.map_leaves(
                lambda _obj: getattr(_obj, "distance_to_boundary")(point, boundary)
            )
        return self._invoke_batch("distance_to_boundary", point, boundary)

    def distance_to_boundary_static(
        self, point: str, boundary, boundary_name: str = None
    ) -> BatchResult:
        """
        Batch-mode wrapper for Features.distance_to_boundary_static
        across the collection.

        See leaf method ``Features.distance_to_boundary_static`` for examples.
        """
        warnings.warn(
            "Direct batch passthrough via FeaturesCollectionBatchMixin.distance_to_boundary_static() is deprecated; "
            "use FeaturesCollection.each.distance_to_boundary_static() instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        _inplace = locals().get("inplace", True)
        if _inplace is False:
            return self.map_leaves(
                lambda _obj: getattr(_obj, "distance_to_boundary_static")(
                    point, boundary, boundary_name
                )
            )
        return self._invoke_batch("distance_to_boundary_static", point, boundary, boundary_name)

    def distance_to_boundary_dynamic(
        self, point: str, boundary, boundary_name: str | None = None
    ) -> BatchResult:
        """
        Batch-mode wrapper for Features.distance_to_boundary_dynamic
        across the collection.

        See leaf method ``Features.distance_to_boundary_dynamic`` for examples.
        """
        warnings.warn(
            "Direct batch passthrough via FeaturesCollectionBatchMixin.distance_to_boundary_dynamic() is deprecated; "
            "use FeaturesCollection.each.distance_to_boundary_dynamic() instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        _inplace = locals().get("inplace", True)
        if _inplace is False:
            return self.map_leaves(
                lambda _obj: getattr(_obj, "distance_to_boundary_dynamic")(
                    point, boundary, boundary_name
                )
            )
        return self._invoke_batch("distance_to_boundary_dynamic", point, boundary, boundary_name)

    def area_of_boundary(self, boundary) -> BatchResult:
        """
        Batch-mode wrapper for Features.area_of_boundary across the collection.

        See leaf method ``Features.area_of_boundary`` for examples.
        """
        warnings.warn(
            "Direct batch passthrough via FeaturesCollectionBatchMixin.area_of_boundary() is deprecated; "
            "use FeaturesCollection.each.area_of_boundary() instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        _inplace = locals().get("inplace", True)
        if _inplace is False:
            return self.map_leaves(lambda _obj: getattr(_obj, "area_of_boundary")(boundary))
        return self._invoke_batch("area_of_boundary", boundary)

    def area_of_boundary_deprecated(self, boundary: list[str], median: bool = True) -> BatchResult:
        """
        Batch-mode wrapper for Features.area_of_boundary_deprecated across the collection.
        """
        warnings.warn(
            "Direct batch passthrough via FeaturesCollectionBatchMixin.area_of_boundary_deprecated() is deprecated; "
            "use FeaturesCollection.each.area_of_boundary_deprecated() instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        _inplace = locals().get("inplace", True)
        if _inplace is False:
            return self.map_leaves(
                lambda _obj: getattr(_obj, "area_of_boundary_deprecated")(boundary, median)
            )
        return self._invoke_batch("area_of_boundary_deprecated", boundary, median)

    def acceleration(self, point: str, dims=("x", "y")) -> BatchResult:
        """
        Batch-mode wrapper for Features.acceleration across the collection.

        See leaf method ``Features.acceleration`` for examples.
        """
        warnings.warn(
            "Direct batch passthrough via FeaturesCollectionBatchMixin.acceleration() is deprecated; "
            "use FeaturesCollection.each.acceleration() instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        _inplace = locals().get("inplace", True)
        if _inplace is False:
            return self.map_leaves(lambda _obj: getattr(_obj, "acceleration")(point, dims))
        return self._invoke_batch("acceleration", point, dims)

    def azimuth(self, point1: str, point2: str) -> BatchResult:
        """
        Batch-mode wrapper for Features.azimuth across the collection.

        See leaf method ``Features.azimuth`` for examples.
        """
        warnings.warn(
            "Direct batch passthrough via FeaturesCollectionBatchMixin.azimuth() is deprecated; "
            "use FeaturesCollection.each.azimuth() instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        _inplace = locals().get("inplace", True)
        if _inplace is False:
            return self.map_leaves(lambda _obj: getattr(_obj, "azimuth")(point1, point2))
        return self._invoke_batch("azimuth", point1, point2)

    def azimuth_deviation(
        self, basepoint: str, pointdirection1: str, pointdirection2: str
    ) -> BatchResult:
        """
        Batch-mode wrapper for Features.azimuth_deviation across the collection.

        Compute the signed angular deviation (radians) between two directions
        from a common basepoint for each frame.

        See leaf method ``Features.azimuth_deviation`` for examples.
        """
        warnings.warn(
            "Direct batch passthrough via FeaturesCollectionBatchMixin.azimuth_deviation() is deprecated; "
            "use FeaturesCollection.each.azimuth_deviation() instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        _inplace = locals().get("inplace", True)
        if _inplace is False:
            return self.map_leaves(
                lambda _obj: getattr(_obj, "azimuth_deviation")(
                    basepoint, pointdirection1, pointdirection2
                )
            )
        return self._invoke_batch("azimuth_deviation", basepoint, pointdirection1, pointdirection2)

    def within_azimuth_deviation(
        self, basepoint: str, pointdirection1: str, pointdirection2: str, deviation: float
    ) -> BatchResult:
        """
        Batch-mode wrapper for Features.within_azimuth_deviation across the collection.

        Return True for frames where the angular deviation between two rays
        from basepoint is <= deviation (radians).
        NA is propagated where inputs are missing (pd.NA).

        See leaf method ``Features.within_azimuth_deviation`` for examples.
        """
        warnings.warn(
            "Direct batch passthrough via FeaturesCollectionBatchMixin.within_azimuth_deviation() is deprecated; "
            "use FeaturesCollection.each.within_azimuth_deviation() instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        _inplace = locals().get("inplace", True)
        if _inplace is False:
            return self.map_leaves(
                lambda _obj: getattr(_obj, "within_azimuth_deviation")(
                    basepoint, pointdirection1, pointdirection2, deviation
                )
            )
        return self._invoke_batch(
            "within_azimuth_deviation", basepoint, pointdirection1, pointdirection2, deviation
        )

    def speed(self, point: str, dims=("x", "y")) -> BatchResult:
        """
        Batch-mode wrapper for Features.speed across the collection.

        See leaf method ``Features.speed`` for examples.
        """
        warnings.warn(
            "Direct batch passthrough via FeaturesCollectionBatchMixin.speed() is deprecated; "
            "use FeaturesCollection.each.speed() instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        _inplace = locals().get("inplace", True)
        if _inplace is False:
            return self.map_leaves(lambda _obj: getattr(_obj, "speed")(point, dims))
        return self._invoke_batch("speed", point, dims)

    def above_speed(self, point: str, speed: float, dims=("x", "y")) -> BatchResult:
        """
        Batch-mode wrapper for Features.above_speed across the collection.

        Return True for frames where the point's speed is >= threshold.
        NA is propagated where inputs are missing (pd.NA).

        See leaf method ``Features.above_speed`` for examples.
        """
        warnings.warn(
            "Direct batch passthrough via FeaturesCollectionBatchMixin.above_speed() is deprecated; "
            "use FeaturesCollection.each.above_speed() instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        _inplace = locals().get("inplace", True)
        if _inplace is False:
            return self.map_leaves(lambda _obj: getattr(_obj, "above_speed")(point, speed, dims))
        return self._invoke_batch("above_speed", point, speed, dims)

    def all_above_speed(self, points: list, speed: float, dims=("x", "y")) -> BatchResult:
        """
        Batch-mode wrapper for Features.all_above_speed across the collection.

        Return True for frames where all listed points are moving at least at the threshold speed.
        NA is propagated: if any input is NA at a frame, result is NA.

        See leaf method ``Features.all_above_speed`` for examples.
        """
        warnings.warn(
            "Direct batch passthrough via FeaturesCollectionBatchMixin.all_above_speed() is deprecated; "
            "use FeaturesCollection.each.all_above_speed() instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        _inplace = locals().get("inplace", True)
        if _inplace is False:
            return self.map_leaves(
                lambda _obj: getattr(_obj, "all_above_speed")(points, speed, dims)
            )
        return self._invoke_batch("all_above_speed", points, speed, dims)

    def below_speed(self, point: str, speed: float, dims=("x", "y")) -> BatchResult:
        """
        Batch-mode wrapper for Features.below_speed across the collection.

        Return True for frames where the point's speed is < threshold.
        NA is propagated where inputs are missing (pd.NA).

        See leaf method ``Features.below_speed`` for examples.
        """
        warnings.warn(
            "Direct batch passthrough via FeaturesCollectionBatchMixin.below_speed() is deprecated; "
            "use FeaturesCollection.each.below_speed() instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        _inplace = locals().get("inplace", True)
        if _inplace is False:
            return self.map_leaves(lambda _obj: getattr(_obj, "below_speed")(point, speed, dims))
        return self._invoke_batch("below_speed", point, speed, dims)

    def all_below_speed(self, points: list, speed: float, dims=("x", "y")) -> BatchResult:
        """
        Batch-mode wrapper for Features.all_below_speed across the collection.

        Return True for frames where all listed points are moving slower than the threshold speed.
        NA is propagated: if any input is NA at a frame, result is NA.

        See leaf method ``Features.all_below_speed`` for examples.
        """
        warnings.warn(
            "Direct batch passthrough via FeaturesCollectionBatchMixin.all_below_speed() is deprecated; "
            "use FeaturesCollection.each.all_below_speed() instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        _inplace = locals().get("inplace", True)
        if _inplace is False:
            return self.map_leaves(
                lambda _obj: getattr(_obj, "all_below_speed")(points, speed, dims)
            )
        return self._invoke_batch("all_below_speed", points, speed, dims)

    def distance_change(self, point: str, dims=("x", "y")) -> BatchResult:
        """
        Batch-mode wrapper for Features.distance_change across the collection.

        Return unsigned distance moved by point from previous to current frame, per frame.

        See leaf method ``Features.distance_change`` for examples.
        """
        warnings.warn(
            "Direct batch passthrough via FeaturesCollectionBatchMixin.distance_change() is deprecated; "
            "use FeaturesCollection.each.distance_change() instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        _inplace = locals().get("inplace", True)
        if _inplace is False:
            return self.map_leaves(lambda _obj: getattr(_obj, "distance_change")(point, dims))
        return self._invoke_batch("distance_change", point, dims)

    def store(
        self, feature: pd.Series, name: str, overwrite: bool = False, meta: dict | None = None
    ) -> BatchResult:
        """
        Batch-mode wrapper for Features.store across the collection.

        Store calculated feature with name and associated freeform metadata.

        See leaf method ``Features.store`` for examples.
        """
        warnings.warn(
            "Direct batch passthrough via FeaturesCollectionBatchMixin.store() is deprecated; "
            "use FeaturesCollection.each.store() instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        _inplace = locals().get("inplace", True)
        if _inplace is False:
            return self.map_leaves(
                lambda _obj: getattr(_obj, "store")(feature, name, overwrite, meta)
            )
        return self._invoke_batch("store", feature, name, overwrite, meta)

    def classify(self, classifier: BaseClassifier, **kwargs) -> BatchResult:
        """
        Batch-mode wrapper for Features.classify across the collection.

        Classify behaviour using a classifier with inputs from this Features object.

        See leaf method ``Features.classify`` for examples.
        """
        warnings.warn(
            "Direct batch passthrough via FeaturesCollectionBatchMixin.classify() is deprecated; "
            "use FeaturesCollection.each.classify() instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        _inplace = locals().get("inplace", True)
        if _inplace is False:
            return self.map_leaves(lambda _obj: getattr(_obj, "classify")(classifier, **kwargs))
        return self._invoke_batch("classify", classifier, **kwargs)

    def smooth(
        self, name: str, method: str, window: int, inplace: bool = False, **method_kwargs
    ) -> BatchResult:
        """
        Batch-mode wrapper for Features.smooth across the collection.

        Smooth feature with method over rolling window. If inplace=True, feature and
        metadata are updated in place.
        method:
            'median' : median in window (numerical)
            'mean' : mean in window (numerical)
            'savgol' : Savitzky–Golay (SciPy). Kwargs e.g. polyorder=3, mode='interp'.
            'mode' : mode in window (numerical or non-numerical)
            'block' : removes labels that occur in blocks of less than length window
                      and replaces them with value from previous block unless there is
                      no previous block, in which case replaced from next block after smoothing
                      note: all nan values will be filled using this method (dangerous!)

        See leaf method ``Features.smooth`` for examples.
        """
        warnings.warn(
            "Direct batch passthrough via FeaturesCollectionBatchMixin.smooth() is deprecated; "
            "use FeaturesCollection.each.smooth() instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        _inplace = locals().get("inplace", True)
        if _inplace is False:
            return self.map_leaves(
                lambda _obj: getattr(_obj, "smooth")(name, method, window, inplace, **method_kwargs)
            )
        return self._invoke_batch("smooth", name, method, window, inplace, **method_kwargs)

    def embedding_df(self, embedding: dict[str, list[int]]) -> BatchResult:
        """
        Batch-mode wrapper for Features.embedding_df across the collection.

        generate a time series embedding dataframe with specified time shifts for each column,
        where embedding is a dict mapping column names to lists of shifts
        positive shift: value from the future (t+n)
        negative shift: value from the past (t-n)

        See leaf method ``Features.embedding_df`` for examples.
        """
        warnings.warn(
            "Direct batch passthrough via FeaturesCollectionBatchMixin.embedding_df() is deprecated; "
            "use FeaturesCollection.each.embedding_df() instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        _inplace = locals().get("inplace", True)
        if _inplace is False:
            return self.map_leaves(lambda _obj: getattr(_obj, "embedding_df")(embedding))
        return self._invoke_batch("embedding_df", embedding)

    def assign_clusters_by_centroids(
        self,
        embedding: dict[str, list[int]],
        centroids_df: pd.DataFrame,
        *,
        scaling_factors: dict[str, float] | None = None,
        impute_medians: pd.Series | None = None,
        rescale_factors: dict | None = None,
        custom_scaling: dict[str, dict] | None = None,
    ) -> BatchResult:
        """
        Batch-mode wrapper for Features.assign_clusters_by_centroids
        across the collection.

        Assign cluster labels to this Features object using pre-fitted centroids.

        See leaf method ``Features.assign_clusters_by_centroids`` for examples.
        """
        warnings.warn(
            "Direct batch passthrough via FeaturesCollectionBatchMixin.assign_clusters_by_centroids() is deprecated; "
            "use FeaturesCollection.each.assign_clusters_by_centroids() instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        _inplace = locals().get("inplace", True)
        if _inplace is False:
            return self.map_leaves(
                lambda _obj: getattr(_obj, "assign_clusters_by_centroids")(
                    embedding,
                    centroids_df,
                    scaling_factors=scaling_factors,
                    impute_medians=impute_medians,
                    rescale_factors=rescale_factors,
                    custom_scaling=custom_scaling,
                )
            )
        return self._invoke_batch(
            "assign_clusters_by_centroids",
            embedding,
            centroids_df,
            scaling_factors=scaling_factors,
            impute_medians=impute_medians,
            rescale_factors=rescale_factors,
            custom_scaling=custom_scaling,
        )

    def train_knn_regressor(
        self,
        *,
        source_embedding: dict[str, list[int]],
        target_embedding: dict[str, list[int]],
        n_neighbors: int = 5,
        normalize_source: bool = False,
        **kwargs,
    ) -> BatchResult:
        """
        Batch-mode wrapper for Features.train_knn_regressor across the collection.

        Developer mode: not available in public release yet.

        See leaf method ``Features.train_knn_regressor`` for examples.
        """
        warnings.warn(
            "Direct batch passthrough via FeaturesCollectionBatchMixin.train_knn_regressor() is deprecated; "
            "use FeaturesCollection.each.train_knn_regressor() instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        _inplace = locals().get("inplace", True)
        if _inplace is False:
            return self.map_leaves(
                lambda _obj: getattr(_obj, "train_knn_regressor")(
                    source_embedding=source_embedding,
                    target_embedding=target_embedding,
                    n_neighbors=n_neighbors,
                    normalize_source=normalize_source,
                    **kwargs,
                )
            )
        return self._invoke_batch(
            "train_knn_regressor",
            source_embedding=source_embedding,
            target_embedding=target_embedding,
            n_neighbors=n_neighbors,
            normalize_source=normalize_source,
            **kwargs,
        )

    def predict_knn(
        self,
        model: KNeighborsRegressor,
        source_embedding: dict[str, list[int]],
        target_embedding: dict[str, list[int]],
        rescale_factors: dict = None,
    ) -> BatchResult:
        """
        Batch-mode wrapper for Features.predict_knn across the collection.

        Developer mode: not available in public release yet.

        See leaf method ``Features.predict_knn`` for examples.
        """
        warnings.warn(
            "Direct batch passthrough via FeaturesCollectionBatchMixin.predict_knn() is deprecated; "
            "use FeaturesCollection.each.predict_knn() instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        _inplace = locals().get("inplace", True)
        if _inplace is False:
            return self.map_leaves(
                lambda _obj: getattr(_obj, "predict_knn")(
                    model, source_embedding, target_embedding, rescale_factors
                )
            )
        return self._invoke_batch(
            "predict_knn", model, source_embedding, target_embedding, rescale_factors
        )

    def define_elliptical_boundary_from_params(
        self,
        centre: str | list[str],
        major_axis_length: float,
        minor_axis_length: float,
        angle_in_radians: float = 0.0,
        n_points: int = 100,
    ) -> BatchResult:
        """
        Batch-mode wrapper for Features.define_elliptical_boundary_from_params
        across the collection.

        Generate a polygonal approximation of an ellipse as a list of (x, y) tuples,
        around `centre` using explicit parameters.
        `centre` can be a point name or list of point names (then centre = mean of medians).

        See leaf method ``Features.define_elliptical_boundary_from_params``
        for examples.
        """
        warnings.warn(
            "Direct batch passthrough via FeaturesCollectionBatchMixin.define_elliptical_boundary_from_params() is deprecated; "
            "use FeaturesCollection.each.define_elliptical_boundary_from_params() instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        _inplace = locals().get("inplace", True)
        if _inplace is False:
            return self.map_leaves(
                lambda _obj: getattr(_obj, "define_elliptical_boundary_from_params")(
                    centre, major_axis_length, minor_axis_length, angle_in_radians, n_points
                )
            )
        return self._invoke_batch(
            "define_elliptical_boundary_from_params",
            centre,
            major_axis_length,
            minor_axis_length,
            angle_in_radians,
            n_points,
        )

    def define_elliptical_boundary_from_points(
        self,
        points: list[str],
        n_points: int = 100,
        scaling: float = 1.0,
        smallness_weight: float = 0.1,
    ) -> BatchResult:
        """
        Batch-mode wrapper for Features.define_elliptical_boundary_from_points
        across the collection.

        Fit an ellipse to the median coordinates of the given tracked points (at least 4)
        and return a polygonal approximation. After fitting, the ellipse is scaled by `scaling`.

        See leaf method ``Features.define_elliptical_boundary_from_points``
        for examples.
        """
        warnings.warn(
            "Direct batch passthrough via FeaturesCollectionBatchMixin.define_elliptical_boundary_from_points() is deprecated; "
            "use FeaturesCollection.each.define_elliptical_boundary_from_points() instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        _inplace = locals().get("inplace", True)
        if _inplace is False:
            return self.map_leaves(
                lambda _obj: getattr(_obj, "define_elliptical_boundary_from_points")(
                    points, n_points, scaling, smallness_weight
                )
            )
        return self._invoke_batch(
            "define_elliptical_boundary_from_points", points, n_points, scaling, smallness_weight
        )
